################################################################################
#  Spring Boot Application Deployment & Service
#  Designed and Developed by: @sak_shetty
#  Description:
#     - Deploys Spring Boot App from DockerHub public image
#     - Waits for MySQL pod readiness before startup
#     - Exposes external LoadBalancer service on NodePort 30088
################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: springapp-ns
  labels:
    app: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z mysql-db 3306; do echo "Waiting for MySQL..."; sleep 5; done; echo "MySQL is up!"']
      containers:
        - name: spring-app
          image: sakit333/webapp_dev:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-db:3306/myapplication?createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"
            - name: SERVER_PORT
              value: "8088"
          ports:
            - containerPort: 8088
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 40
            periodSeconds: 20
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "700Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-svc
  namespace: springapp-ns
  labels:
    app: spring-app
spec:
  type: LoadBalancer
  selector:
    app: spring-app
  ports:
    - name: http
      port: 8088
      targetPort: 8088
      nodePort: 30088
